import { Application } from '@/features/dashboard/components/application-card'

export const mockApplications: Application[] = [
  {
    id: '1',
    name: 'Promptly',
    clerkId: 'creative-app-98.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '7 hours ago',
    hasProductionEnvironment: false,
  },
  {
    id: '2',
    name: 'NewTube',
    clerkId: 'humane-hawk-61.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '20 days ago',
    hasProductionEnvironment: false,
  },
  {
    id: '3',
    name: 'docs',
    clerkId: 'musical-amoeba-64.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '2 months ago',
    hasProductionEnvironment: false,
  },
  {
    id: '4',
    name: 'discord-clone',
    clerkId: 'patient-oyster-61.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '8 months ago',
    hasProductionEnvironment: false,
  },
  {
    id: '5',
    name: 'nuxt-auth',
    clerkId: 'civil-starfish-61.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '8 months ago',
    hasProductionEnvironment: false,
  },
  {
    id: '6',
    name: 'lingo',
    clerkId: 'quality-stag-22.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '9 months ago',
    hasProductionEnvironment: false,
  },
  {
    id: '7',
    name: 'Miro',
    clerkId: 'wanted-heron-30.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '9 months ago',
    hasProductionEnvironment: false,
  },
  {
    id: '8',
    name: 'Finance',
    clerkId: 'fun-swine-51.clerk.accounts.dev',
    plan: 'Free Plan',
    updatedAt: '10 months ago',
    hasProductionEnvironment: false,
  },
]
