'use client'

import { motion } from 'motion/react'

import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Card, CardContent } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'

const testimonials = [
  {
    quote:
      'Promptly has completely transformed how I interact with AI coding assistants. My code quality has improved dramatically.',
    author: 'Alex Morgan',
    role: 'Senior Developer',
    avatar: '/avatars/alex.jpg',
    initials: 'AM',
  },
  {
    quote:
      "The precision of the prompts generated by Promptly is incredible. I'm getting exactly the code I need on the first try.",
    author: 'Sarah Chen',
    role: 'Full Stack Engineer',
    avatar: '/avatars/sarah.jpg',
    initials: 'SC',
  },
  {
    quote:
      'As a team lead, Promptly has helped standardize how our entire team communicates with AI tools. Huge productivity boost!',
    author: 'Michael Rodriguez',
    role: 'Engineering Manager',
    avatar: '/avatars/michael.jpg',
    initials: 'MR',
  },
  {
    quote:
      'I was skeptical at first, but the difference in code quality when using Promptly-optimized prompts is night and day.',
    author: 'Jamie Wilson',
    role: 'Frontend Developer',
    avatar: '/avatars/jamie.jpg',
    initials: 'JW',
  },
]

export function Testimonials() {
  return (
    <section className="bg-muted/30 py-20">
      <div className="container mx-auto px-4 md:px-6">
        <div className="mb-12 flex flex-col items-center justify-center text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="mb-4 text-3xl font-bold tracking-tight md:text-4xl">
              What Developers Are Saying
            </h2>
            <p className="mx-auto max-w-3xl text-xl text-muted-foreground">
              Join thousands of satisfied developers who have improved their AI
              coding workflow with Promptly.
            </p>
          </motion.div>
          <Separator className="mx-auto my-8 max-w-md" />
        </div>

        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          {testimonials.map((testimonial, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
            >
              <Card className="h-full border-none shadow-md transition-shadow duration-300 hover:shadow-lg">
                <CardContent className="p-6">
                  <div className="flex h-full flex-col">
                    <div className="mb-4">
                      <svg
                        className="h-8 w-8 text-primary/40"
                        fill="currentColor"
                        viewBox="0 0 32 32"
                        aria-hidden="true"
                      >
                        <path d="M9.352 4C4.456 7.456 1 13.12 1 19.36c0 5.088 3.072 8.064 6.624 8.064 3.36 0 5.856-2.688 5.856-5.856 0-3.168-2.208-5.472-5.088-5.472-.576 0-1.344.096-1.536.192.48-3.264 3.552-7.104 6.624-9.024L9.352 4zm16.512 0c-4.8 3.456-8.256 9.12-8.256 15.36 0 5.088 3.072 8.064 6.624 8.064 3.264 0 5.856-2.688 5.856-5.856 0-3.168-2.304-5.472-5.184-5.472-.576 0-1.248.096-1.44.192.48-3.264 3.456-7.104 6.528-9.024L25.864 4z" />
                      </svg>
                    </div>
                    <p className="mb-6 flex-grow text-lg">
                      {testimonial.quote}
                    </p>
                    <div className="flex items-center">
                      <Avatar className="mr-4 h-10 w-10">
                        <AvatarImage
                          src={testimonial.avatar}
                          alt={testimonial.author}
                        />
                        <AvatarFallback>{testimonial.initials}</AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="font-medium">{testimonial.author}</p>
                        <p className="text-sm text-muted-foreground">
                          {testimonial.role}
                        </p>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
